from pydantic import BaseModel, Field 
from typing import List, Dict, Any, Optional, Union

class MedicationDetails(BaseModel):
        medication_name: Optional[str] = Field(default=None, description="The name of the medication")
        generic_name: Optional[str] = Field(default=None, description="Generic name of the medication")
        ingredients: List[str] = Field(default_factory=list, description="Active and inactive chemical components")
        brand_names: List[str] = Field(default_factory=list, description="List of brand names for this medication")
        medicine_use: Optional[str] = Field(default=None, description="Primary uses and conditions this medication treats")
        common_side_effects: List[str] = Field(default_factory=list, description="Common side effects")
        severe_side_effects: List[str] = Field(default_factory=list, description="Severe or rare side effects")
        immediate_attention_side_effects: List[str] = Field(default_factory=list, description="Side effects requiring immediate medical attention")
        how_to_use: Optional[str] = Field(default=None, description="Instructions on dosage, timing, and administration")
        storage_instructions: Optional[str] = Field(default=None, description="Guidelines for proper storage")
        mechanism_of_action: Optional[str] = Field(default=None, description="How the medicine works in the body")
        warnings_precautions: List[str] = Field(default_factory=list, description="Special warnings and precautions")
        alternative_medicines: List[str] = Field(default_factory=list, description="Similar or alternative medications")
        natural_alternatives: List[str] = Field(default_factory=list, description="Herbal or dietary alternatives if mentioned")
        regulatory_approval: Optional[str] = Field(default=None, description="Approval status from health authorities")
        drug_interactions: Optional[str] = Field(default=None, description="Information about potential drug interactions")
        forms_variants: List[str] = Field(default_factory=list, description="Available forms such as tablets, injections, etc.")
        prescription_required: Optional[bool] = Field(default=None, description="Whether the medication requires a prescription")
        contraindications: List[str] = Field(default_factory=list, description="Conditions where the medication should not be used")
        drug_class: Optional[str] = Field(default=None, description="The class or category of the drug")
        pregnancy_lactation: Optional[str] = Field(default=None, description="Information regarding use during pregnancy or breastfeeding")
        dosage_forms: List[str] = Field(default_factory=list, description="Specific dosage forms available")
        special_populations_children: Optional[str] = Field(default=None, description="Special instructions for children")
        special_populations_elderly: Optional[str] = Field(default=None, description="Special instructions for the elderly")
        special_populations_renal_impairment: Optional[str] = Field(default=None, description="Special instructions for individuals with renal impairment")
        special_populations_hepatic_impairment: Optional[str] = Field(default=None, description="Special instructions for individuals with hepatic impairment")
        overdose_information: Optional[str] = Field(default=None, description="Information about overdose symptoms and management")
        reviews_rating: Optional[str] = Field(default=None, description="Rating based on user reviews")
